### ISSUE TITLE
W/KitApi(17211): error reading iBeacon data:java.lang.NullPointerException

### ISSUE THREAD

**Issue by saifrahmed** [RadiusNetworks/proximity-reference-android#1] opened 2014-04-21 03:12 UTC
I set up the AndroidProximityLibrary and the android-proximity-reference, referencing the prior.  The applications dont have any resolution or build issues.  However, when launching the android-proximity-reference, I get a warning:
W/KitApi(17211): error reading iBeacon data:java.lang.NullPointerException
The application does launch but does not appear to detect any nearby beacons.

(I'm assuming the error is with the AndroidProximityLibrary, but since that isnt on this GitHub I figured I should log the bug here.)

**Comment by davidgyoung** [comment] 2014-04-21 21:55
Thanks for the report.   This bug was caused by an empty set of key/value pairs for a defined beacon in your kit.  This should have been allowed.  It is fixed in this version of the library:

http://s3.amazonaws.com/android-ibeacon-library.radiusnetworks.com/AndroidProximityLibrary-1.1.2.4.tar.gz

**Closed as completed by davidgyoung** 2014-04-21 21:55 UTC

**Comment by TedAvery** [comment] 2014-05-29 23:56
Hi David, thanks for your help here and via e-mail. The library looks really robust, but I keep running into issues because I don't have the latest library. The [developer portal download page](http://proximitykit.com/kits/1808/download/android) still redirects to version 1.1.1, this sample project has 1.1.2.3 (which I was just e-mailed the link to last night), and now I'm having this same bug, which  I now see was patched back on April 22 in an even more recent version 1.1.2.4 which I've only seen on this GitHub issue. The main SDK links in the developer portal should really point to the latest version so these little bugs can be avoided.

**Comment by davidgyoung** [comment] 2014-05-30 00:44
Fair point, Ted.  We do usually wait to link to individual bug fix releases (e.g. 1.1.2.4) until we get enough developer feedback to roll them into a stable release (e.g. 1.1.3).  But you correctly noted that we apparently never linked to 1.1.2.  Since we are overdue in that, and have done ample testing with 1.1.2.4, I have gone ahead and rolled a new 1.1.3 release and linked to it on the developer download page.
